version: "3.9"

services:
  api:
    image: python:3.12-slim
    working_dir: /app
    environment:
      FLASK_ENV: development
      PORT: 8101
      DATABASE_URL: sqlite:///./data/lifeform.db
      PYTHONPATH: /app
    volumes:
      - ./:/app
      - ./data:/app/data
      - ./logs:/app/logs
    command: sh -c "pip install --no-cache-dir -r requirements.txt && flask --app wsgi:app run --host=0.0.0.0 --port=8101"
    ports:
      - "8101:8101"
    healthcheck:
      test: ["CMD", "python", "-c", "import urllib.request; urllib.request.urlopen('http://127.0.0.1:8101/health').read()"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

  web:
    image: node:20
    working_dir: /app/frontend
    environment:
      NEXT_PUBLIC_API_BASE_URL: http://localhost:8101
    volumes:
      - ./:/app
    command: sh -c "npm install && npm run dev -- --hostname 0.0.0.0 --port 3101"
    ports:
      - "3101:3101"
    depends_on:
      api:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "node", "-e", "fetch('http://127.0.0.1:3101').then(()=>{},()=>process.exit(1))"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 20s
